-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Bnfc.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Bnfc.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Bnfc.Abs.Ident -> Result
transIdent x = case x of
  Bnfc.Abs.Ident string -> failure x

transProgram :: Show a => Bnfc.Abs.Program' a -> Result
transProgram x = case x of
  Bnfc.Abs.Prog _ stmts -> failure x

transStmt :: Show a => Bnfc.Abs.Stmt' a -> Result
transStmt x = case x of
  Bnfc.Abs.SAss _ ident exp -> failure x
  Bnfc.Abs.SExp _ exp -> failure x

transExp :: Show a => Bnfc.Abs.Exp' a -> Result
transExp x = case x of
  Bnfc.Abs.ExpAdd _ exp1 exp2 -> failure x
  Bnfc.Abs.ExpSub _ exp1 exp2 -> failure x
  Bnfc.Abs.ExpMul _ exp1 exp2 -> failure x
  Bnfc.Abs.ExpDiv _ exp1 exp2 -> failure x
  Bnfc.Abs.ExpLit _ integer -> failure x
  Bnfc.Abs.ExpVar _ ident -> failure x
