apiVersion: v1
kind: Service
metadata:
  name: website # Sets service name
  labels:
    app: website # Labels and Selectors
spec:
  type: LoadBalancer # Sets service type
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: website
