apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  EMAILS_QUEUE_NAME: "emails-queue"
  USER_SERVICE_ADDR: "http://users.default.svc.cluster.local"
  NEWSLETTER_SERVICE_ADDR: "http://newsletters.default.svc.cluster.local"


