apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: users-go-image
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
